import { Scrobbles } from "../models/domain";

export const testScrobbles: Scrobbles = [
  {
    mbid: "TEST",
    name: "TESTNAME",
    album: {
      mbid: "TEST",
      name: "Agony",
      artist: {
        mbid: "TEST",
        name: "Fleshgod Apocalypse",
        country: "",
        image: "",
        url: "",
      },
      releaseDate: "",
      image: "",
      url: "",
    },
    artist: {
      mbid: "TEST",
      name: "Fleshgod Apocalypse",
      country: "",
      image: "",
      url: "",
    },
    url: "https://www.last.fm/music/Fleshgod+Apocalypse/_/The+Imposition",
    date: "1621423317",
  },
  {
    mbid: "TEST2",
    name: "TESTNAME2",
    album: {
      mbid: "TEST2",
      name: "Agony",
      artist: {
        mbid: "TEST2",
        name: "Fleshgod Apocalypse",
        country: "",
        image: "",
        url: "",
      },
      releaseDate: "",
      image: "",
      url: "",
    },
    artist: {
      mbid: "TEST2",
      name: "Fleshgod Apocalypse",
      country: "",
      image: "",
      url: "",
    },
    url: "https://www.last.fm/music/Fleshgod+Apocalypse/_/The+Hypocrisy",
    date: "1621423019",
  },
  // {
  //   mbid: "1d6cf7cf-1709-3860-9fa8-79c2381ceed7",
  //   name: "Temptation",
  //   album: {
  //     mbid: "5eacd540-3a94-4a00-8d15-e48807c42b64",
  //     name: "Agony",
  //     artist: {
  //       mbid: "48cb4248-889d-45ed-8462-acb29c002a8d",
  //       name: "Fleshgod Apocalypse",
  //       country: "",
  //       image: "",
  //       url: "",
  //     },
  //     releaseDate: "",
  //     image: "",
  //     url: "",
  //   },
  //   artist: {
  //     mbid: "48cb4248-889d-45ed-8462-acb29c002a8d",
  //     name: "Fleshgod Apocalypse",
  //     country: "",
  //     image: "",
  //     url: "",
  //   },
  //   url: "https://www.last.fm/music/Fleshgod+Apocalypse/_/Temptation",
  //   date: "1621422687",
  // },
  // {
  //   mbid: "ec829173-9187-3ccb-90da-30e09edcb16f",
  //   name: "Mafia",
  //   album: {
  //     mbid: "9fc351ef-6f46-4f03-8f25-999b22615331",
  //     name: "Mafia",
  //     artist: {
  //       mbid: "48cb4248-889d-45ed-8462-acb29c002a8d",
  //       name: "Fleshgod Apocalypse",
  //       country: "",
  //       image: "",
  //       url: "",
  //     },
  //     releaseDate: "",
  //     image: "",
  //     url: "",
  //   },
  //   artist: {
  //     mbid: "48cb4248-889d-45ed-8462-acb29c002a8d",
  //     name: "Fleshgod Apocalypse",
  //     country: "",
  //     image: "",
  //     url: "",
  //   },
  //   url: "https://www.last.fm/music/Fleshgod+Apocalypse/_/Mafia",
  //   date: "1621422580",
  // },
  // {
  //   mbid: "cef2ae40-53fd-3afa-83ff-b21a0c3071d8",
  //   name: "Blinded by Fear",
  //   album: {
  //     mbid: "9fc351ef-6f46-4f03-8f25-999b22615331",
  //     name: "Mafia",
  //     artist: {
  //       mbid: "48cb4248-889d-45ed-8462-acb29c002a8d",
  //       name: "Fleshgod Apocalypse",
  //       country: "",
  //       image: "",
  //       url: "",
  //     },
  //     releaseDate: "",
  //     image: "",
  //     url: "",
  //   },
  //   artist: {
  //     mbid: "48cb4248-889d-45ed-8462-acb29c002a8d",
  //     name: "Fleshgod Apocalypse",
  //     country: "",
  //     image: "",
  //     url: "",
  //   },
  //   url: "https://www.last.fm/music/Fleshgod+Apocalypse/_/Blinded+by+Fear",
  //   date: "1621422397",
  // },
];
