import { Scrobbles } from "../models/domain";

export const testScrobbles: Scrobbles = [
  {
    mbid: "TEST",
    name: "The Forsaking",
    album: {
      mbid: "TESTALBUM",
      name: "Agony",
      artist: {
        mbid: "TESTARTIST",
        name: "Fleshgod Apocalypse",
        country: "",
        image: "",
        url: "",
      },
      releaseDate: "",
      image: "",
      url: "",
    },
    artist: {
      mbid: "TEST",
      name: "Fleshgod Apocalypse",
      country: "",
      image: "",
      url: "",
    },
    url: "",
    date: "1621423317",
  },
  {
    mbid: "TEST2",
    name: "Only Pain",
    album: {
      mbid: "TESTALBUM2",
      name: "Magma",
      artist: {
        mbid: "TESTARTIST2",
        name: "Gojira",
        country: "",
        image: "",
        url: "",
      },
      releaseDate: "",
      image: "",
      url: "",
    },
    artist: {
      mbid: "TEST2",
      name: "Gojira",
      country: "",
      image: "",
      url: "",
    },
    url: "",
    date: "1621423019",
  },
  {
    mbid: "TEST3",
    name: "Empty Words",
    album: {
      mbid: "TESTALBUM3",
      name: "Symbolic",
      artist: {
        mbid: "TESTARTIST3",
        name: "Death",
        country: "",
        image: "",
        url: "",
      },
      releaseDate: "",
      image: "",
      url: "",
    },
    artist: {
      mbid: "TESTARTIST3",
      name: "Death",
      country: "",
      image: "",
      url: "",
    },
    url: "",
    date: "1621422687",
  },
];

export const testScrobbles2: Scrobbles = [
  {
    mbid: "TEST4",
    name: "Atomb",
    album: {
      mbid: "TESTALBUM4",
      name: "Nuklearth",
      artist: {
        mbid: "TESTARTIST4",
        name: "Cytotoxin",
        country: "",
        image: "",
        url: "",
      },
      releaseDate: "",
      image: "",
      url: "",
    },
    artist: {
      mbid: "TEST4",
      name: "Cytotoxin",
      country: "",
      image: "",
      url: "",
    },
    url: "",
    date: "1621423317",
  },
  {
    mbid: "TEST5",
    name: "Naraka",
    album: {
      mbid: "TESTALBUM5",
      name: "Samsara",
      artist: {
        mbid: "TESTARTIST5",
        name: "Venom Prison",
        country: "",
        image: "",
        url: "",
      },
      releaseDate: "",
      image: "",
      url: "",
    },
    artist: {
      mbid: "TEST5",
      name: "Venom Prison",
      country: "",
      image: "",
      url: "",
    },
    url: "",
    date: "1621423019",
  },
  {
    mbid: "TEST6",
    name: "We Are Nil",
    album: {
      mbid: "TESTALBUM6",
      name: "Everything Is Fire",
      artist: {
        mbid: "TESTARTIST6",
        name: "Ulcerate",
        country: "",
        image: "",
        url: "",
      },
      releaseDate: "",
      image: "",
      url: "",
    },
    artist: {
      mbid: "TESTARTIST6",
      name: "Ulcerate",
      country: "",
      image: "",
      url: "",
    },
    url: "",
    date: "1621422687",
  },
];
